@startuml

class RequestA {
    -someNumber
    -someString
    -someOtherRecord : SomeOtherRecord
}


class SomeOtherRecord {
    -someOtherString
    -someOtherNumber
}

RequestA --> SomeOtherRecord

class ResponseA {
    -List<SomeOtherResponseA> someOtherResponseAs
}

class SomeOtherResponseA{
    -someResponseStr
    -someBigDecimal
    -someOtherBigDecimal
}

ResponseA -up-> SomeOtherResponseA


class RequestB{
    -someDouble
    -List<SomeOtherResponseA> someOtherResponseAs
}

RequestB --> SomeOtherResponseA

class ResponseB{
    mapOf
     SomeKey someKey => SomeOtherResponseB someOtherResponseB
}
class SomeKey{
    -someStrKey
    -someDoubleKey
}

class SomeOtherResponseB{
    -someString
    -someBigDecimal
}

ResponseB --> SomeOtherResponseB
ResponseB --> SomeKey

class FinalResponse{
    -List<SomeOtherResponseA> someOtherResponseAs
    -someOtherResponseB
}

FinalResponse -up-> SomeOtherResponseA
FinalResponse -up-> SomeOtherResponseB

@enduml
